FROM sres.web.boeing.com:5000/python:3.11-slim


USER root


WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY torch-2.9.0+cpu-cp311-cp311-manylinux_2_28_x86_64.whl .
RUN pip install torch-2.9.0+cpu-cp311-cp311-manylinux_2_28_x86_64.whl

#Install system packages
RUN apt-get update && apt-get install -y --no-install-recommends \
        build-essential gcc \
        git \
        curl \
        libsqlite3-dev \
    && rm -rf /var/lib/apt/lists*

RUN curl http://crl.boeing.com/crl/Boeing%20Basic%20Assurance%20Software%20Issuing%20CA%20G3.crt | openssl x509 -inform DER -out  /etc/ssl/certs/Boeing-Bundle-CA.pem
RUN curl http://crl.boeing.com/crl/Boeing%20Basic%20Assurance%20Software%20Root%20CA%20G2.crt | openssl x509 -inform DER >>  /etc/ssl/certs/Boeing-Bundle-CA.pem
RUN update-ca-certificates
RUN export REQUESTS_CA_BUNDLE=/etc/ssl/certs/boeing-bundle-ca.pem

COPY . .
EXPOSE 8000

ENV PYTHONPATH=.
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1 \
    HF_HOME=/app/models TRANSFORMERS_OFFLINE=1 HF_HUB_OFFLINE=1

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]