version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      # - data-volume:/data  # Mounts the volume to /data in the container (named volume); Docker manages the storage location internally.
      - "C:/Users/ki163f/Documents/Projects/13. AI_ML_Training/PersistenceStorageDemo/data:/data" #mount a specific host folder instead of a named volume; (/data) is the path inside the container.
    environment:
      - DATA_DIR=/data     # Ensures the app uses the volume for storage


volumes:
  data-volume:
